name: Simple Test Workflow

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Simple notification
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const timestamp = new Date().toISOString();
            const event = context.eventName;
            const body = `## ✅ テスト通知
            
            ワークフローが正常に動作しています！
            
            - イベント: ${event}
            - 時刻: ${timestamp}`;
            
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: 2,
              body: body
            });
